# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Ranysha Ware
email: rware@cs.swarthmore.edu
first_name: Ranysha
middle_name: 
last_name: Ware
description: > # this means to ignore newlines until "url:"
   Ranysha Ware's homepage
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: https://www.cs.swarthmore.edu
baseurl: /~rware
last_updated: false

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: rware
twitter_username: ranyshaware
linkedin_username: # your LinkedIn user name
scholar_userid: # your Google Scholar ID
semanticscholar_id: # your Semantic Scholar ID
orcid_id: 0009-0001-6619-4149
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
dblp_url: # your DBLP profile url
stackoverflow_id: # your stackoverflow id
kaggle_id: # your kaggle id
lastfm_id: # your lastfm id
spotify_id: # your spotify id
pinterest_id: # your pinterest id
unsplash_id: # your unsplash id
instagram_id: # your instagram id
facebook_id: # your facebook id
youtube_id: # your youtube channel id (youtube.com/@<youtube_id>)
discord_id: # your discord id (18-digit unique numerical identifier)

contact_note: >
  Email is the best way to reach me.

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------
google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
panelbear_analytics: # panelbear analytics site ID
google_site_verification: # your google-site-verification ID
bing_site_verification: # your Bing verification code
baidu_site_verification: # your Baidu verification code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: rware
blog_description: academic

# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

permalink: /blog/:year/:title/

# Comments (set to true to enable)
disqus_shortname: al-folio
giscus:
  repo: # <your-github-username>/<your-github-repo-name>
  repo_id: 
  category: Comments
  category_id: 
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

# Optional features
show_social_icons: false
enable_anchorjs: false
enable_katex: true
enable_google_analytics: false
enable_panelbear_analytics: false
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    defaults:
      layout: post
    output: true
    permalink: /publications/:path

news_limit: 5
news_scrollable: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - vendor

keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jemoji

# Jekyll-Archives
jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

# Jekyll-Scholar
scholar:
  last_name: [Ware]
  first_name: [Ranysha]

  style: _styles/acm-sig-proceedings-long-author-list.csl
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  
  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  
  group_by: year
  group_order: descending

# Display different badges on the publication page
enable_publication_badges:
  altmetric: true
  dimensions: true

# Filter out certain bibtex entry keywords used internally
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website, preview, altmetric]

# Maximum number of authors to show
max_author_limit: 3
more_authors_animation_delay: 10

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------
imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-quality 75%"

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------
jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.13.11"
anchorjs_version: "4.3.1"
